function censusTransformValue = censusTransform(image, x, y)
censusTransformValue = uint8(0);
center = image(x, y);
neighbors = [image(x-1, y-1)...
             image(x,   y-1)...
             image(x+1, y-1)...
             image(x-1, y  )...
             image(x+1, y  )...
             image(x-1, y+1)...
             image(x,   y+1)...
             image(x+1, y+1)];
for i = 1:length(neighbors)
  if center >= neighbors(i)
    censusTransformValue = bitset(censusTransformValue, i);
  end
end
end

