function censusTransformValue = censusTransform(image, x, y)

  function neighbours = neighbourPixels(image, x, y)
    neighbours = [image(y-1, x-1)...
                  image(y-1, x  )...
                  image(y-1, x+1)...
                  image(y  , x-1)...
                  image(y  , x+1)...
                  image(y+1, x-1)...
                  image(y+1, x  )...
                  image(y+1, x+1)];
  end

censusTransformValue = uint8(0);
center = image(x, y);
neighbours = neighbourPixels(image, x, y);
for i = 1:length(neighbours)
  if center >= neighbours(i)
    censusTransformValue = bitset(censusTransformValue, i);
  end
end
end
