function censusTransformValue = censusTransform(image, x, y)

  function neighbours = neighbourPixels(image, x, y)
    neighbours = [image(x-1, y-1)...
                  image(x,   y-1)...
                  image(x+1, y-1)...
                  image(x-1, y  )...
                  image(x+1, y  )...
                  image(x-1, y+1)...
                  image(x,   y+1)...
                  image(x+1, y+1)];
  end

censusTransformValue = uint8(0);
center = image(x, y);
neighbours = neighbourPixels(image, x, y);
for i = 1:length(neighbours)
  if center >= neighbours(i)
    censusTransformValue = bitset(censusTransformValue, i);
  end
end
end

