function [spactDatabase, pcaLoadings, columnMeans] = updateDatabase(directory)
  function absoluteFilenames = imageList(directory)
    images = dir(fullfile(directory, '*.jpg'));
    absoluteFilenames = arrayfun(@(x) fullfile(directory, x.name), ...
                                 images, ...
                                 'UniformOutput', false);
  end
filenames = imageList(directory);
centristDatabase = centristFiles(filenames);
columnMeans = mean(centristDatabase);
pcaLoadings = princomp(centristDatabase);
spactDatabase = spactFiles(filenames, pcaLoadings, columnMeans);
cacheDir = fullfile(directory, 'cache');
if ~exist(cacheDir, 'dir')
  % make sure there is a cache directory
  mkdir(cacheDir)
end
save(fullfile(cacheDir, 'centristDatabase.mat'), ...
     'centristDatabase', ...
     'filenames');
save(fullfile(cacheDir, 'spactDatabase.mat'), ...
     'spactDatabase', ...
     'pcaLoadings', ...
     'columnMeans', ...
     'filenames');
end
